on:
  push:
    branches:
      - master
  release:
    types: [published]

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: node

  merge-to-prod:
    runs-on: ubuntu-latest
    needs: release-please
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "DET-BOT"
          git config user.email "det-bot@users.noreply.github.com"

      - name: Merge master into prod
        run: |
          git fetch origin prod
          git checkout prod
          git merge origin/master --no-edit
          git push origin prod